export class AppModel {
  pageWidth: number;
  pageHeight: number;
  pageResolution: number;
  blockType: string;
  blockName: string;
  blockLeft: number;
  blockRight: number;
  blockTop: number;
  blockBottom: number;
  blockCenterCoords: number;
  blockWidth: number;
  blockHeight: number;
  parAlign: string;
  parStartIndent: string;
  parLineSpacing: string;
  lineBaseline: number;
  lineLeft: number;
  lineRight: number;
  lineBottom: number;
  lineTop: number;
  lang: string;
  fieldValue: string;
  cellWidth: number;
  cellHeight: number;
  blockId: number;
  pageId: number;
  parId; number;
  lineCenterX: number;
  lineCenterY: number;
  probabilityInvoiceNumber: number;
  probabilityInvoiceNumberColor = 0;
  probInvoiceNumPositionWeight: number;
  probInvoiceNumKeyDistanceWeight: number;
  probInvoiceNumStructureWeight: number;
  probInvoiceLineStructureWeight: number;

  probabilityInvoiceDateCreate: number;
  probabilityInvoiceDateCreateColor = 0;
  probInvoiceDateCreatePositionWeight: number;
  probInvoiceDateCreateRangeWeight: number;
  probInvoiceDateCreateAlignWeight: number;
  probInvoiceDateCreateDateStructureWeight: number;
}
